spring:
    application:
        name: Review

    thymeleaf:
        cache: false
        enabled: true 
        prefix: 'classpath:/templates/'
        suffix: '.html'

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://ec2-3-209-65-193.compute-1.amazonaws.com:5432/ddl8nttqis05in
        username: hamlgcebswgrpz
        password: df793145e3ae9c3f29da745f9388f892be1f14eec25ea477435cd12f1120e7db
    jpa:
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8081

app:
    title: 'Avaliações'
    menu: 'Menu'

games:
    auth-url: https://id.twitch.tv/oauth2
    base-url: https://api.igdb.com/v4
    client-id: yozprgxbepc57kp2bcd9lk8tdopuxf
    secret: xlokokzuj7ghron7ux9w0bwu0zqfie
    grant-type: client_credentials
    connect-timeout: 5000
    read-timeout: 10000